<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <AssemblyName>ParsecClipboardIsolator</AssemblyName>
    <RootNamespace>ParsecClipboardIsolator</RootNamespace>
    <Product>Parsec Clipboard Isolator</Product>
    <Title>Parsec Clipboard Isolator</Title>

    <!-- Native AOT Настройки -->
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>

</Project>
